# Generated by Django 5.1.7 on 2025-04-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProdi',
            fields=[
                ('id_prodi', models.AutoField(primary_key=True, serialize=False)),
                ('prodi', models.CharField(max_length=255)),
                ('deskripsi_singkat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul_smt1_d3', models.JSONField(default=list)),
                ('matkul_smt2_d3', models.JSONField(default=list)),
                ('matkul_smt3_d3', models.JSONField(default=list)),
                ('matkul_smt4_d3', models.JSONField(default=list)),
                ('matkul_smt5_d3', models.JSONField(default=list)),
                ('matkul_smt6_d3', models.JSONField(default=list)),
                ('matkul_smt1_d4', models.JSONField(default=list)),
                ('matkul_smt2_d4', models.JSONField(default=list)),
                ('matkul_smt3_d4', models.JSONField(default=list)),
                ('matkul_smt4_d4', models.JSONField(default=list)),
                ('matkul_smt5_d4', models.JSONField(default=list)),
                ('matkul_smt6_d4', models.JSONField(default=list)),
                ('matkul_smt7_d4', models.JSONField(default=list)),
                ('matkul_smt8_d4', models.JSONField(default=list)),
                ('id_prodi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.infoprodi')),
            ],
        ),
        migrations.CreateModel(
            name='UserForML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang_pendidikan', models.CharField(max_length=50)),
                ('program_studi', models.CharField(max_length=255)),
                ('minat_bakat', models.JSONField(default=list)),
                ('jalur_pendaftaran', models.CharField(max_length=100)),
                ('rata_nilai', models.FloatField()),
                ('rencana_karir', models.TextField()),
                ('prodi_rekomendasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.infoprodi')),
            ],
        ),
    ]
