# Generated by Django 5.2 on 2025-05-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History_Rekomendasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jenjang_pendidikan', models.CharField(max_length=100)),
                ('minat_dan_bakat', models.TextField()),
                ('jalur_pendaftaran', models.CharField(max_length=100)),
                ('rencana_karir', models.CharField(max_length=100)),
                ('rata_rata_nilai_masuk_pens', models.FloatField()),
                ('hasil_rekomendasi', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'history_rekomendasi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InfoProdi',
            fields=[
                ('id_prodi', models.AutoField(primary_key=True, serialize=False)),
                ('prodi', models.CharField(max_length=255)),
                ('deskripsi_singkat', models.TextField()),
            ],
            options={
                'db_table': 'infoprodi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matkul_smt1_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt2_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt3_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt4_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt5_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt6_d3', models.TextField(blank=True, null=True)),
                ('matkul_smt1_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt2_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt3_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt4_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt5_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt6_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt7_d4', models.TextField(blank=True, null=True)),
                ('matkul_smt8_d4', models.TextField(blank=True, null=True)),
                ('prospek_kerja', models.TextField(blank=True, null=True)),
                ('link_website', models.TextField(blank=True, null=True)),
                ('id_prodi_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.infoprodi')),
            ],
            options={
                'db_table': 'matkul',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserForML',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jenjang_pendidikan', models.CharField(max_length=50)),
                ('minat_bakat', models.TextField()),
                ('jalur_pendaftaran', models.TextField()),
                ('rata_nilai', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rencana_karir', models.TextField()),
                ('prodi_rekomendasi_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.infoprodi')),
            ],
            options={
                'db_table': 'userforml',
                'managed': True,
            },
        ),
    ]
