# Generated by Django 5.1.7 on 2025-04-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoprodi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matkul',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userforml',
            options={'managed': False},
        ),
    ]
